/*
  Fields defined using:
  ```
  head -n 1 /app/data/companiesHouse/basicCompanyData.cs
  ```
*/

create table basic_company_data (
  company_name text,
  company_number text primary key,
  registered_address_care_of text,
  registered_address_po_box text,
  registered_address_address_line_1 text,
  registered_address_address_line_2 text,
  registered_address_post_town text,
  registered_address_county text,
  registered_address_country text,
  registered_address_post_code text,
  company_category text,
  company_status text,
  country_of_origin text,
  dissolution_date text,
  incorporation_date text,
  accounts_account_ref_day text,
  accounts_account_ref_month text,
  accounts_next_due_date text,
  accounts_last_made_up_date text,
  accounts_account_category text,
  returns_next_due_date text,
  returns_last_made_up_date text,
  mortgages_num_mort_charges text,
  mortgages_num_mort_outstanding text,
  mortgages_num_mort_part_satisfied text,
  mortgages_num_mort_satisfied text,
  sic_code_sic_text_1 text,
  sic_code_sic_text_2 text,
  sic_code_sic_text_3 text,
  sic_code_sic_text_4 text,
  limited_partnerships_num_gen_partners text,
  limited_partnerships_num_lim_partners text,
  uri text,
  previous_name_1_con_date text,
  previous_name_1_company_name text,
  previous_name_2_con_date text,
  previous_name_2_company_name text,
  previous_name_3_con_date text,
  previous_name_3_company_name text,
  previous_name_4_con_date text,
  previous_name_4_company_name text,
  previous_name_5_con_date text,
  previous_name_5_company_name text,
  previous_name_6_con_date text,
  previous_name_6_company_name text,
  previous_name_7_con_date text,
  previous_name_7_company_name text,
  previous_name_8_con_date text,
  previous_name_8_company_name text,
  previous_name_9_con_date text,
  previous_name_9_company_name text,
  previous_name_10_con_date text,
  previous_name_10_company_name text,
  conf_stmt_next_due_date text,
  conf_stmt_last_made_up_date text
);
